### ISSUE TITLE
Network Read Failure (FemasAPI)

### ISSUE THREAD

**Issue by thraneh** [quinclas/issues#1]
Sometimes we observe the market data feed simply stops updating.

**FrontDisconnected with network read error**.
The API doesn't recover if we try to reconnect. We have observed re-ordering of messages (exchange timestamp was reported out-of-order).
**Solution**: Current action is to terminate the gateway and let the managing process restart it.

**Not recovering after midday session break**.
No indication of network errors. Starting a new gateway receives updates while currently running gateway doesn't. Nothing found in the logs indicating errors.
**TODO**: Add event counter logging to understand if the various threads are functional.
**TODO**: Investigate if there any API methods we can use to send "heartbeat" to the broker. (Previous investigation didn't reveal any).
**TODO**: Feels like last-resort solution -- restart gateway just before the 2nd session starts.

**Comment by thraneh** [comment]
**Done**: Added event counters
**Done**: Fixed issue where encoding variables were used across different threads without mutual exclusion. The solution involves using distinct encoding variables per thread and only minimally lock-time when iterating over client connections.
**Done**: Restart (issue FATAL log message) when seeing network read error.

**Comment by thraneh** [comment]
Seeing way too many network read errors (100s) during a session for automatic restart to be a valid solution. Reverting this change and hoping the gateway lock-up was due to threading issues.
It didn't make any difference whether the gateway was running from China or abroad (Great Firewall).
**TODO**: Investigate logs to understand if network read error is still an issue (we saw re-ordering of received messages).
**TODO**: Also capture and log metrics about last update from the OnPackageStart/OnPackageEnd API callbacks (we don't log the actual events because they're too plentiful).

**Comment by thraneh** [comment]
**Status**:

Without gateway restart, we're seeing
- Regular disconnects (reason: network read error),
- Automatic reconnect after about 5 seconds, and
- Messages arriving out-of-order (indicated by the exchange timestamp).

So far no gateway lock-ups.

**Comment by xugangmarsh** [comment]
Regular disconnects (reason: network read error)----- could u pls post the error msg ?
Automatic reconnect after about 5 seconds, and ------  no loggings or any msgs ?
Messages arriving out-of-order (indicated by the exchange timestamp) ------ will reach out the broker.

**Comment by thraneh** [comment]
You're right, this issue was not reported with all details. Let me improve on that.

These are the initialization steps;

```
I0110 05:40:59.106783 22470 md_user.cpp:45] GetVersion() = "Lnx64 Femas_AllFutures_1.01 L300" (major=1, minor=1)
I0110 05:40:59.107095 22470 md_user.cpp:49] CreateFtdcMduserApi() = 0x121f100
I0110 05:40:59.107115 22470 md_user.cpp:23] RegisterSpi(pSpi=0x7ffc9624f900)
I0110 05:40:59.107128 22470 md_user.cpp:65] RegisterFront(pszFrontAddress="tcp://222.68.181.130:8105")
I0110 05:40:59.107136 22470 md_user.cpp:65] RegisterFront(pszFrontAddress="tcp://222.68.181.130:5213")
I0110 05:40:59.107275 22470 md_user.cpp:95] SubscribeMarketDataTopic(nTopicID=DIALOG, nResumeType=QUICK)
I0110 05:40:59.107426 22470 md_user.cpp:95] SubscribeMarketDataTopic(nTopicID=PRIVATE, nResumeType=QUICK)
I0110 05:40:59.107576 22470 md_user.cpp:95] SubscribeMarketDataTopic(nTopicID=PUBLIC, nResumeType=QUICK)
I0110 05:40:59.107702 22470 md_user.cpp:95] SubscribeMarketDataTopic(nTopicID=QUERY, nResumeType=QUICK)
I0110 05:40:59.107834 22470 md_user.cpp:95] SubscribeMarketDataTopic(nTopicID=USER, nResumeType=QUICK)
I0110 05:40:59.107859 22470 md_user.cpp:95] SubscribeMarketDataTopic(nTopicID=QUOTE, nResumeType=QUICK)
I0110 05:40:59.107879 22470 md_user.cpp:95] SubscribeMarketDataTopic(nTopicID=UNKNOWN:100, nResumeType=QUICK)
I0110 05:40:59.108005 22470 md_user.cpp:95] SubscribeMarketDataTopic(nTopicID=UNKNOWN:21001, nResumeType=QUICK)
I0110 05:40:59.109314 22470 md_user.cpp:138] Init()
I0110 05:40:59.329645 22471 md_user.cpp:159] OnFrontConnected()
I0110 05:40:59.329771 22471 md_user.cpp:105] SubMarketData(ppInstrumentID=["IF1801", "IF1802", "IF1803", "IF1806", "IC1801", "IC1802", "IC1803", "IC1806", "IH1801", "IH1802", "IH1803", "IH1806", "TF1803", "TF1806", "T1803", "T1806"], nCount=16) = 0
I0110 05:40:59.329792 22471 md_user.cpp:57] GetTradingDay() = "20180110"
I0110 05:40:59.329983 22471 md_user.cpp:127] ReqUserLogin( ** HAVE REMOVED DETAILS ** ) = 0
I0110 05:40:59.553864 22471 md_user.cpp:213] OnRspUserLogin(pRspUserLogin={TradingDay="20180110", ** HAVE REMOVED DETAILS ** , LoginTime="", ExchangeTime="", MaxOrderLocalID="                   0", TradingSystemName="ÖÐ½ð¼¼ÊõÐÐÇéÏµÍ³", DataCenterID=0, PrivateFlowSize=0, UserFlowSize=0, ActionDay="", FemasVersion="", FemasLifeCycle=0}, pRspInfo={ErrorID=NONE, ErrorMsg="ÕýÈ·"}, nRequestID=0, bIsLast=1)
I0110 05:40:59.561172 22471 md_user.cpp:249] OnRtnDepthMarketData(pDepthMarketData={TradingDay="20180110", SettlementGroupID="SG01", SettlementID=1, PreSettlementPrice=96.67, PreClosePrice=96.665, PreOpenInterest=1025, PreDelta=1.79769e+308, OpenPrice=96.585, HighestPrice=96.665, LowestPrice=96.455, ClosePrice=1.79769e+308, UpperLimitPrice=97.83, LowerLimitPrice=95.51, SettlementPrice=1.79769e+308, CurrDelta=1.79769e+308, LastPrice=96.57, Volume=131, Turnover=1.2651e+08, OpenInterest=1033, BidPrice1=96.545, BidVolume1=2, AskPrice1=96.595, AskVolume1=4, BidPrice2=96.42, BidVolume2=3, AskPrice2=96.72, AskVolume2=2, BidPrice3=1.79769e+308, BidVolume3=0, AskPrice3=96.755, AskVolume3=2, BidPrice4=1.79769e+308, BidVolume4=0, AskPrice4=1.79769e+308, AskVolume4=0, BidPrice5=1.79769e+308, BidVolume5=0, AskPrice5=1.79769e+308, AskVolume5=0, InstrumentID="TF1806", UpdateTime="13:40:54", UpdateMillisec=700, ActionDay="", HisHighestPrice=0, HisLowestPrice=0, LatestVolume=0, InitVolume=0, ChangeVolume=0, BidImplyVolume=0, AskImplyVolume=0, AvgPrice=0, ArbiType=UNDEFINED, InstrumentID_1="", InstrumentID_2="", InstrumentName="", TotalBidVolume=0, TotalAskVolume=0})
```

After many `OnRtnDepthMarketData` callbacks, we then see

```
I0110 05:50:47.066824 22471 md_user.cpp:165] OnFrontDisconnected(nReason=NETWORK_READ_FAILURE)
I0110 05:50:52.301900 22471 md_user.cpp:159] OnFrontConnected()
```

With no callbacks in between. That's a 5 second delay for reconnect.

I then proceed to repeat the steps shown already -- I send the request to login and then I subscribe market data. It then looks ok for about 10 seconds before it happens again.

This is a grep on `"OnFront"`;

```
I0110 05:40:59.329645 22471 md_user.cpp:159] OnFrontConnected()
I0110 05:50:47.066824 22471 md_user.cpp:165] OnFrontDisconnected(nReason=NETWORK_READ_FAILURE)
I0110 05:50:52.301900 22471 md_user.cpp:159] OnFrontConnected()
I0110 05:50:57.589157 22471 md_user.cpp:165] OnFrontDisconnected(nReason=NETWORK_READ_FAILURE)
I0110 05:51:02.824380 22471 md_user.cpp:159] OnFrontConnected()
I0110 05:51:08.120857 22471 md_user.cpp:165] OnFrontDisconnected(nReason=NETWORK_READ_FAILURE)
I0110 05:51:13.371954 22471 md_user.cpp:159] OnFrontConnected()
I0110 05:51:18.726127 22471 md_user.cpp:165] OnFrontDisconnected(nReason=NETWORK_READ_FAILURE)
I0110 05:51:23.925671 22471 md_user.cpp:159] OnFrontConnected()
I0110 05:51:29.167022 22471 md_user.cpp:165] OnFrontDisconnected(nReason=NETWORK_READ_FAILURE)
I0110 05:51:34.393892 22471 md_user.cpp:159] OnFrontConnected()
```

I don't have any current examples with messages arriving out of order. I will update if and when I see it again.

**Comment by thraneh** [comment]
I have reviewed the code some more and not really found any further issues which could be related to threading. It should also not really matter since everything described above is read-only from the MDUser interface.

However, I have now added regular logging of last seen sequence number from the OnPackageStart/End callbacks. The intention is to monitor the "aliveness" of the API listener threads. It's not directly related to the symptoms seen above. But nevertheless useful.

I have also tried to not initialize the Trader API. My thinking was that maybe MDUser and Trader was conflicting with each other. This test didn't show any improvement. MDUser is still disconnecting due to network read failure.

Some further thoughts;

The disconnect comes after about 10 seconds. It could be a timeout somewhere. Or it could be a message type not understood by the API we're using.

Questions;

- Do we have to configure or send heartbeats? (I don't find anything by looking at the API code).
- Are we using the latest API version?

**Comment by thraneh** [comment]
Upon reviewing the code, I realise C callbacks (from the FemasAPI) were unprotected from exceptions passing the boundary. I have now added try-catch for all exceptions.

**Comment by thraneh** [comment]
Gang, in response to your questions you posted to me.

_Q: it seems you have got already many level mktdepth update, have you checked those  OnRtnDepthMarketData callbacks, are they all valid market data level updates ?_

Market data looks good after the initial connection (although we only get top of book);

```
I0111 06:33:01.556886 11174 md_user.cpp:249] OnRtnDepthMarketData(pDepthMarketData={TradingDay="20180111", SettlementGroupID="SG01", SettlementID=1, PreSettlementPrice=96.515, PreClosePrice=96.515, PreOpenInterest=1035, PreDelta=1.79769e+308, OpenPrice=96.465, HighestPrice=96.495, LowestPrice=96.15, ClosePrice=1.79769e+308, UpperLimitPrice=97.67, LowerLimitPrice=95.36, SettlementPrice=1.79769e+308, CurrDelta=1.79769e+308, LastPrice=96.31, Volume=234, Turnover=2.25441e+08, OpenInterest=1075, BidPrice1=96.31, BidVolume1=3, AskPrice1=96.485, AskVolume1=2, BidPrice2=96.185, BidVolume2=6, AskPrice2=1.79769e+308, AskVolume2=0, BidPrice3=1.79769e+308, BidVolume3=0, AskPrice3=1.79769e+308, AskVolume3=0, BidPrice4=1.79769e+308, BidVolume4=0, AskPrice4=1.79769e+308, AskVolume4=0, BidPrice5=1.79769e+308, BidVolume5=0, AskPrice5=1.79769e+308, AskVolume5=0, InstrumentID="TF1806", UpdateTime="14:31:16", UpdateMillisec=100, ActionDay="", HisHighestPrice=0, HisLowestPrice=0, LatestVolume=0, InitVolume=0, ChangeVolume=0, BidImplyVolume=0, AskImplyVolume=0, AvgPrice=0, ArbiType=UNDEFINED, InstrumentID_1="", InstrumentID_2="", InstrumentName="", TotalBidVolume=0, TotalAskVolume=0})
```

The market data updates also look good after reconnects (here jumping a bit in time because the initial reconnects are pre-open, we just keep getting yesterday's last update);

```
I0111 07:11:19.698819 11174 md_user.cpp:249] OnRtnDepthMarketData(pDepthMarketData={TradingDay="20180111", SettlementGroupID="SG01", SettlementID=1, PreSettlementPrice=96.515, PreClosePrice=96.515, PreOpenInterest=1035, PreDelta=1.79769e+308, OpenPrice=96.465, HighestPrice=96.505, LowestPrice=96.15, ClosePrice=1.79769e+308, UpperLimitPrice=97.67, LowerLimitPrice=95.36, SettlementPrice=1.79769e+308, CurrDelta=1.79769e+308, LastPrice=96.34, Volume=274, Turnover=2.64011e+08, OpenInterest=1094, BidPrice1=96.315, BidVolume1=9, AskPrice1=96.365, AskVolume1=4, BidPrice2=96.19, BidVolume2=8, AskPrice2=96.49, AskVolume2=3, BidPrice3=1.79769e+308, BidVolume3=0, AskPrice3=1.79769e+308, AskVolume3=0, BidPrice4=1.79769e+308, BidVolume4=0, AskPrice4=1.79769e+308, AskVolume4=0, BidPrice5=1.79769e+308, BidVolume5=0, AskPrice5=1.79769e+308, AskVolume5=0, InstrumentID="TF1806", UpdateTime="15:11:19", UpdateMillisec=100, ActionDay="", HisHighestPrice=0, HisLowestPrice=0, LatestVolume=0, InitVolume=0, ChangeVolume=0, BidImplyVolume=0, AskImplyVolume=0, AvgPrice=0, ArbiType=UNDEFINED, InstrumentID_1="", InstrumentID_2="", InstrumentName="", TotalBidVolume=0, TotalAskVolume=0})
```

_Q: if so, then if seems we got md updates already, but after 10 mins client(your code) is disconnected from the server_

It's not 10 minutes. We see updates for 10 **seconds**, then disconnect.

_Q: if so, then if seems we got md updates already, but after 10 mins client(your code) is disconnected from the server_

Correct, I don't do anything for the reconnect. The API does everything.

_Q: it looks to me that we dont need to re-do the login/subscribe_

I will try to modify the code to not repeat those steps after reconnect.

_Q: after onFrontConnected, you still receive market data you subscribed ? or there is no market data update anymore ?_

I still receive market data after reconnects.

_Q: you said ... >>>>>> (again -- i don't know what to use for query_front and name_server)_

It seems to me that we have to register to two different servers -- (a) for order management and (b) for request/response queries.
USTPFtdcTraderApi.h:
void RegisterFront(char *pszFrontAddress)
void RegisterQryFront(char *pszFrontAddress)
I only ever got the address details for the first function...

**Comment by thraneh** [comment]
Testing is ongoing and the issues are still present.

**Observations**:

- Ansible deployment to the Shanghai server was not correct. The collector was trying to connect to the wrong socket. The gateway saw read failures until about 10:28 CST, then no failures for 4 hours until 14:17 CST. The collector was finally connected to the correct port at 14:06 CST. This is confusing because (a) the read failures happened early in the day irrespective the collector was not connected, (b) the network seemed ok for almost 4 hours, (c) read failures started happening again about 10 minutes after the collector connected. Frequency is the same that we have observed all along -- disconnects happen every 10 seconds.

- The test running from a server in Europe also saw the network read failures. However, at 02:28 UTC (08:28 CST) it stopped working. Of 5 threads, 4 were still working (the FemasAPI threads). It appears the last thread (the libevent/epoll loop) was still alive, but not doing anything. This was confirmed by querying for metrics (new feature) using `curl http://localhost:12345/metrics` - this operation was hanging, i.e. indicating the server side still was bound to the port, but not processing the request. No exceptions were to be found in the logs.

- Experiments with the resume type showed that all 3 (`QUICK`, `RESUME`, `RESTART`) options cause network read failure. The config was always using `QUICK` and we will keep it that way. (We don't want to replay historical event / just get the initial image).

**Interpretation**:

- It is not possible right now to say whether the network read failures are caused by the libevent thread or the UAT environment. It seems likely that it is an issue with the implementation of the event loop, though. Perhaps dead-lock? Or missing Tx/Rx flow control?

**Next steps**:

- Another review of the code to look for threading issues. Further reduce locking, where possible. In particular, investigate if dead-locking could occur.
- Implement a watchdog for the event loop. Issue a self-kill if the event loop stops responding.
- Complete the Prometheus metrics monitoring. This will help us correlate gateway behavior with other system metrics.
- Implement support for native libevent logging (`event_set_log_callback` and/or `event_enable_debug_logging`).
- Understand how to create and debug a core dump. Perhaps we can then find out where the event loo was stuck.

**Notes**:

- libevent automatically issues `exit()` or `abort()` when its internal data structures are corrupted. We don't see this happening. Indications are therefore towards the implementation.

**Comment by thraneh** [comment]
A few more observation to what was just mentioned.

Having disconnected the collector from the gateway (around 15:05 CST), there are still network read failures about every 10 seconds.

The exchange opening hours are also from 09:30 to 15:00 CST. Today we saw network read failures until 10:30 and after 14:30 CST. Perhaps the UAT environment was just good for 4 hours?

Speculation, of course... (The action points just mentioned should nevertheless be implemented).

**Comment by thraneh** [comment]
Having made some change, still seeing network errors. The issue still remains.

Changes and experiments

- Verified MDUser and Trader each only calls back from a single thread.
- Further reducing the time spent on locking a mutex between the FemasAPI callback and the libevent loop.
- Moving access to atomic variables outside the mutex lock section.
- Without registering the name server (and query server for Trader).
- Without having any client (collector) connected to the gateway.
- Monitoring the time spent in each FemasAPI callback.

On the last point, the documentation states that the API can disconnect the client if it's not responding quickly enough.

For reference, the distribution of time spent in callback duration

| duration (usec)  | count    |
| ---------------: | -------: |
|                   <100 |           0 |
|             100-200 |  32,157 |
|            200-300 |   11,189 |
|            300-400 |    5,061 |
|            400-500 |         60 |
|          500-1000 |        216 |
|                >1000 |        252 |

(*) min = 101, max = 1744

This distribution is not acceptable, of course. However, we're currently using a debug build and logging excessively (with little focus on optimizations).

The feed is throttled and only sending updates once a second (the `OnRtnDepthMarketData` callback). We have subscribed 16 instruments.

Some worst case estimates;
Duration spent in callbacks should range between 1.6 (16 * 0.1) and 27.2 (16 * 1.7) milliseconds. Average is probably around 4 milliseconds.

So we spend worst-case 2.7% of the time processing callbacks. (Averaging around 0.4%).

**Comment by thraneh** [comment]
Today there has been **no issues** related to network read failures.

- The gateway started up without any clients listening.
- The collector was later connected.

More and more the indication is towards a poor UAT experience.

**Comment by thraneh** [comment]
We believe the issue was with the UAT environment. Closing this issue.

**Comment by thraneh** [comment]
The real reason: We had multiple client processes connecting to the broker. The broker will automatically disconnect the clients when this happens. Doh!
